name: islami
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    -  assets/images/
